[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[MODELS.OPENAI]
API_KEY = ""

[MODELS.GROQ]
API_KEY = ""

[MODELS.ANTHROPIC]
API_KEY = ""

[MODELS.GEMINI]
API_KEY = ""

[MODELS.OLLAMA]
API_URL = "http://localhost:11434"

[MODELS.CUSTOM_OPENAI]
API_URL = ""
API_KEY = ""
MODEL_NAME = ""

[API_ENDPOINTS]
SEARXNG = "http://localhost:8080"
