use_default_settings: true

general:
  debug: false
  instance_name: "Omni Search"

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "19cfdb4f-25d1-492b-8f81-6ff89be01cc5"
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true

engines:
  - name: google
    engine: google
    shortcut: g
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
  - name: github
    engine: github
    shortcut: gh
  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
  - name: arxiv
    engine: arxiv
    shortcut: ar
  - name: wikipedia
    engine: wikipedia
    shortcut: w

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0
